apiVersion: v1
kind: Service
metadata:
  labels:
    app: stress-api
    env: master
  name: stress-api-service
spec:
  type: NodePort
  selector:
    app: stress-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32022
      name: http